name: Friends Backup

on:
  schedule:
    - cron: "0 0 * * 1"

  pull_request: [master]

jobs:
  release:
    name: Main job
    runs-on: ubuntu-latest
    steps:
      # Every step starts with '-'
      - uses: actions/checkout@v2

      - name: Create environment
        uses: conda-incubator/setup-miniconda@v2
        with:
            environment-file: environment.yml
            activate-environment: twitter
            channels: conda-forge, defaults
            mamba-version: "*"

      - name: Run main script
        shell: bash -l {0}
        run: |
          python -m friends
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}

      - uses: actions/upload-artifact@v1
        with:
          name: epassaros-friends
          path: epassaros_friends.csv
