name: Backup Twitter Following List

on:
  schedule:
    - cron: "0 23 * * *"

jobs:
  release:
    name: Main job
    runs-on: ubuntu-latest
    steps:
      # Every step starts with '-'
      - uses: actions/checkout@v2

      - name: Create environment
        uses: goanpeca/setup-miniconda@v1.0.2
        with:
          auto-update-conda: True
          activate-environment: twitter
          environment-file: environment.yml
          auto-activate-base: False

      - name: Run main script
        shell: bash -l {0}
        run: |
          python -m main.py
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}

      - uses: actions/upload-artifact@v1
        with:
          name: friends-list
          path: friends.csv
